# Generated by Django 2.2.4 on 2019-08-23 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_album_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
