# Generated by Django 2.2.4 on 2019-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190823_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('administration_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'administration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_content', models.CharField(max_length=16384)),
                ('posting_num', models.IntegerField()),
                ('reposting_num', models.IntegerField()),
                ('new_reply_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
