# Generated by Django 2.2.4 on 2019-08-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_administration_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbPosting',
            fields=[
                ('thumb_posting_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'thumb_posting',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThumbReposting',
            fields=[
                ('thumb_reposting_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'thumb_reposting',
                'managed': False,
            },
        ),
    ]
